version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install --save
      - run:
          name: run some tests    
          command: |
            npm test    
workflows:
  backend_tests:
    jobs:
      - run_tests
